### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ivaigult** [intel/fastuidraw#22]
While I was doing _Travis-CI_ build enabling I encountered very strange issue:

> No rule to make target `build/demo/debug/GL/demos/atlas_tests/image_test/main.o

I can not reproduce this on my local machine.

Here is [the link](https://travis-ci.org/ivaigult/fastuidraw/builds/296254143) to Travis build.

Any ideas?

**Comment by krogueintel** [comment]
Hi,

There are two ideas I have:
1. The top of the build process says that sdl2-config is missing; SDL2 is not needed to build the FastUIDraw libraries, but it is needed to build the demos. It might be that make barfs out on dependency stuff because it fails to make the dependency file, main.d; that file is only needed to build a demo. One easy way out is to instead of doing "make all" to instead just build the .so's with "make libFastUIDrawGL" which should build both debug and release GL backend libs which in turn have dependency so that the base debug and release get built. 

2. Sadly, the build system for FastUIDraw relies on GNU make instead of vanilla make. One thing I have seen is that some particular versions of GNU make don't do the right thing for the rules and freak out.

My personal hunch is (1) is the most likely.

By the way for what are you using FastUIDraw?
