### ISSUE TITLE
Fixes required for building under macOS

### ISSUE THREAD

**Issue by Sakari369** [intel/fastuidraw#25]
Just to let you know, I built this library with the following fixes under macOS High Sierra:

- add include for string in 'src/fastuidraw/text/glyph_selector.cpp'
- replace 'soname' in all the makefiles under make/ with 'install_name'

The first fix is trivial, the second one not so, I see you have already a CMake build in the process, so that might fix the soname issue also.

With this at least the base library libFastUIDraw target builds succesfully. The backends I did not get yet compiling due to different GL headers.

Would be interested in seeing this run on macOS too. Let's see if I get the macOs version running, I see you already had somebody do that on an older version, I'll try that.

**Comment by Sakari369** [comment]
Ok after quickly trying to apply just the build rules from the old macOS build fixes, I get forwards, but seems the OpenGL changes are not exactly trivial to fix, so not taking a more indepth look currently. Maybe testing this first on Linux to see.

**Comment by boruis** [comment]
meet the same problem, can't compile on macos.

**Comment by krogueintel** [comment]
I've added some #ifdef __APPLE__ tweaks to a few places in the source files. To build on OS-X, one now needs to do:

- modify makefiles to correctly build the dynamic library (as inDigiNeous has)
- set the environmental variables:
-- GL_RAW_HEADER_FILES = OpenGL/gl3.h
-- GL_INCLUDEPATH = path/where/OpenGL/directory/resides

Let me know of any compiling fails you see and I will try to fix them. This is a touch tricky since I do not have an OS-X box to test on, or even the OpenGL/gl3.h header Apple platform uses.

I think it will build now, but another issue reported that OS-X GL drivers had serious issues trying to compile the uber-shaders. This might have improved since then though.

**Comment by krogueintel** [comment]
Sighs.. Apple has listed OpenGL as deprecated on macOS. As such, getting FastUIDraw to work on MacOS with the GL back end is now dead. I still want have FastUIDraw work there, but it will need to be done by a Metal back end.

**Comment by ytain** [comment]
OpenGL will still be present in the future macOS versions till Apple decides to rip it out of the innards of the OS. However it is marked as deprecated in the upcoming SDKs that accompany the XCode releases. So you can still use it for a while. The only issue is that OpenGL drivers on macOS will not gain new versions or features or even fixes.

There's also another alternative called MoltenGL, which offers OpenGL ES 2.0 on top of Metal.

https://moltengl.com/moltengl/

**Comment by krogueintel** [comment]
Here are the beans on FastUIDraw on Apple platforms.

1. I **want** to support FastUIDraw on OS-X and also iOS.
2. I do not have any such hardware myself on which to do development.
3. The GL on OS-X was/is not in good shape, there was an issue earlier where someone got FastUIDraw to build and then all the painter demos either locked the machine or crashed. The likely cause is that the shader compiler could not handle the complicated shaders that FastUIDraw uses. The upshot is that the GL driver on OS-X needs to be fixed/updated which is not going to happen.
4. As for MoltenGL, the bare minimum for FastUIDraw is OpenGL ES 3.0; OpenGL ES 2.0 lacks way too many features (the biggest are native integer format, UBOs, floating point textures) and in truth ES 3.1 is much, much better since is has SSBO's.
5. The correct thing to do for all of the Apple platforms is to write a backend in Metal. The main pain for this is that all the shaders will need to be rewritten in Metal as well which is over 7000 lines of GLSL code. The total size of the GL and GLSL modules together is about 30,000 lines of code. If I am to do a Metal backend I anticipate that the Metal backend would be -smaller- though (this is because the GL and GLSL modules are for handling both GL and GLES along with the myriad of ways of doing similar operations through different GL/GLES extentsion and GL/GLES versions).

If I had hardware, I could do it in my spare time, but I don't. 

I've been toying with the idea of making a Vulkan backend for FastUIDraw for ages and there is a Vulkan on top of Metal too (https://moltengl.com/moltenvk/) but I will also need to include something to create/compile the uber-shaders at runtime from GLSL sources (this does exist on github as well from Khronos). The main caveat is that Vulkan lacks the functionality that some GL extensions offer namely: GL_EXT_shader_framebuffer_fetch or one of GL_ARB_fragment_shader_interlock, GL_NV_fragment_shader_interlock, GL_INTEL_fragment_shader_ordering. One thing about MoltenVK is that I think it allows one to feed Metal Shaders to it as well, which means I can do the string magic and then have a Vulkan backend that only works on Apple platforms. 

However, I think that the Metal API does offer something like GL_EXT_shader_framebuffer_fetch atleast on iOS which is why the Metal backend for the Apple platforms is the way to go I think.
