### ISSUE TITLE
Artifacts in painter-path-test-GL-release

### ISSUE THREAD

**Issue by ChengCat** [intel/fastuidraw#26]
When I built fastuidraw and run the demos, I noticed some artifacts.

![fastuidraw](https://user-images.githubusercontent.com/33503784/38122923-b822f446-33c7-11e8-80a6-38bfcdf58097.png)

Is this expected? Thanks.

**Comment by krogueintel** [comment]
Sadly: YES.

The way to remove the artifact is to stroke the path without shader based anti-aliasing (toggled by the 'a'-key). If one wants anti-aliasing still, then one needs to start up with msaa (use --help to find the options).

The cause of the artifacts is from the shader based anti-aliasing that draws some anti-alias "smudging" around the stroking and some times it double draws. I can get rid most of the of the double draw by changing how a stroked path is realized, but this makes dashed stroking potentially wonking and still leaves over-draw at places where the path crosses itself. Another way to kill the overdraw comes at the cost of a different artifact where smudging is missing when a path crosses itself. 

I have on my internal road map a method to remove the artifact entirely (without resorting to msaa) but it requires a GL implementation with either
1.  both GL_ARB_shader_image_load_store AND GL_ARB_fragment_shader_interlock OR 
2.  GL_EXT_shader_framebuffer_fetch

For both cases, on desktop devices, AMD does not have either of these; Both NVIDIA (newer) and Intel (all the way back to Ivy Bridge) have (1) HW-capable wise and (2) is on Intel since Skylake; on the driver side, NVIDIA is same regardless of MS-Windows or Linux (as long as one uses NVIDIA's closed source driver) where as for Intel, option (1) is fine under MS-Windows but not on Linux and (2) is fine for both.

Another approach to remove the artifact is potentially performance harming where stroking takes 2 distinct API states; I am really not enthusiastic about this because for scenes with hundreds of strokes will have a significant performance penalty.

**Comment by ChengCat** [comment]
Thanks for the detailed explanation. I am looking forward to the better implementations.

**Comment by krogueintel** [comment]
I have just implemented the infrastructure and additional shaders to support better shader-based anti-aliasing. The basic idea of the implementation is to provide an auxiliary coverage buffer that is filled first and then used and cleared when drawing content to the framebuffer. There are several modes, controlled by the command line argument **provide_auxiliary_image_buffer** 
- **no_auxiliary_buffer** means to not use an auxiliary buffer, which will give rendering issue on paths with shader based anti-aliasing. This value is also the default.
- **auxiliary_buffer_atomic** uses atomic ops; the requirement is GL4.2/GLES3.1 (or GL3.3 with GL_ARB_shader_image_load_store). This is a poor performing option since it will create two draw call breaks per path stroked. However, it should work on AMD cards and for that matter very old NVIDIA cards too.
- **auxiliary_buffer_interlock**  uses the extension *GL_INTEL_fragment_shadering_ordering* and should give good performance as it does not issue any draw call breaks. The requirements are that extension together with the requirements of  **auxiliary_buffer_atomic**. As of now, the only driver I know that implements the needed extension is the Intel GPU driver (starting with quite old GPU, IvyBridge) on MS-Windows
- **auxiliary_buffer_interlock_main_only** uses the extension *GL_ARB_fragment_shader_interlock* OR *GL_NV_fragment_shader_interlock* and should also give good performance as it does not issue any draw call breaks. The requirements are one of those extensions together with the requirements of  **auxiliary_buffer_atomic**. Newer NVIDIA proprietary drivers for their newer GPU's should have this extension, in addition the Intel GPU drivers (again starting way back to IvyBridge) on MS-Windows should also have the extension. Of note is that there was a patch series for Mesa on Intel GPU implementing the functionality quite some time ago, but the series was not merged into master sadly.
- **auxiliary_buffer_framebuffer_fetch** only requires the extension *GL_EXT_shader_framebuffer_fetch* and GL3.3/GLES3.0. This should give good performance as it does not issue any draw call breaks.  This extension should be present on newer NVIDIA proprietary drivers with newer GPU's, is present on Intel GPU starting in Skylake (Gen9) in both MS-Windows and Linux in Mesa 18.0)

Lastly, one can also resort to MSAA for anti-aliased path rendering (in this case, then no auxiliary buffer is used). To enable the painter to draw with MSAA, add the option "painter_msaa N" where N is the number of samples per-pixel one wishes to use. The default value is 1, indicating no MSAA.

The options **auxiliary_buffer_framebuffer_fetch**, **auxiliary_buffer_interlock_main_only** and **auxiliary_buffer_interlock** are the best performance options. As to which is faster: **auxiliary_buffer_atomic** or using **painter_msaa**, is harder to decide and quite likely highly load dependent.

**Comment by ChengCat** [comment]
It looks like a great solution. Thank you!

I have just tested same demo again with `provide_auxilary_image_buffer` set to `auxilary_buffer_framebuffer_fetch`, the previous artifacts are gone now. Unfortunately, I noticed another type of artifacts when fill is toggled on by pressing `f`:

![artifacts](https://user-images.githubusercontent.com/33503784/38558706-78fd6830-3cc0-11e8-8ae4-d11c124bd040.png)

These artifacts are more visible when slowly scaling the image. If it matters, I expect fastuidraw to fall back to `auxiliary_buffer_atomic` in my test environment.

p.s.: There's a typo in the demo `--help` output:

> auxilary_buffer_interlock:Auxilary buffer
> ...
> and GL 4.2 (or GL_ARB_shader_image_load_store
> extension[typo here]; if requirements are not satisfied
> ...

**Comment by krogueintel** [comment]
The logic of the auxilary buffer is: if it can do an auxilary buffer and if one is asked for, it will give you one, even if it is the dreaded atomic implementation.

Typo (hopefully) fixed now; if not (because there were actually several it turned out), give me a pull request.

As for that rendering issue, I am 99% sure it is not path stroking that is the culprit, but shader based anti-aliasing path filling. Hit 'f' key and use the '[' to make the stroking width go to zero. If it is the shader-based anti-aliasing that is the culprit, then it is caused by that the anti-alias fuzz around the fill is dropping a pixel at the some of the corners where two line segments of the tessellated path meet, i.e. exterior corners. I have a way to handle this, it is essentially adding the analogue of a bevel join between neighboring edges for the anti-alias fuzz of a filled path. However, that is going to take some time to implement because it needs the neighboring edge information and that requires walking an edge list and trying to figure out a contour from a winding component. ick.

The other thing that is... ugly about this is that the 1-pixel is missing issue is highly numerically unstable, so the artifact might depend on GPU. Out of curiosity, what GPU and driver are you using?

Check if you are getting the anomaly from filling and if so, lets make a fresh issue for it because it is about filling, not stroking.

**Comment by krogueintel** [comment]
Yep, the shade-based anti-aliasing filling is an issue and not good enough for filling paths when the fill color is transparent. It is exhibiting similar issues that shader based-anti-aliased stroking did.

I added the command line options stroke_XXX and fill_XXX there XXX is red, green, blue or alpha to the painter-path-test command line. Making fill_alpha 0.5, and making the stroking width 0.0 (by holding '[') I can see that on the curvy path there is all sorts of anti-alias overdraw. Sighs.

Work will be forthcoming to deal with this; I think the idea of just drawing a 1-pixel fuzz on the fill-path boundary edges is not going to work out; I have some other ideas that I did not pursue to completion, but this will take awhile to resurrect and get ready.

**Comment by ChengCat** [comment]
> As for that rendering issue, I am 99% sure it is not path stroking that is the culprit, but shader based anti-aliasing path filling. Hit 'f' key and use the '[' to make the stroking width go to zero.

Yes, I tried that, and the issue seems to be related to anti-aliased fills.

> Making fill_alpha 0.5, and making the stroking width 0.0 (by holding '[') I can see that on the curvy path there is all sorts of anti-alias overdraw.

I confirm that I see a lot of artifacts too.

> Out of curiosity, what GPU and driver are you using?

NVIDIA GeForce GTX 760, with NVIDIA proprietary Linux driver (version 390.25).

I'll close this issue and create a new one. Thanks again for the work, and I continue looking forward to the fixes.
