### ISSUE TITLE
Artifacts with shader-based anti-aliasing filling

### ISSUE THREAD

**Issue by ChengCat** [intel/fastuidraw#27]
Steps to reproduce:
1. run one of the demos with `./painter-path-test-GL-release fill_alpha=0.5`
2. press `f` key to toggle filling on
3. hold `[` key until the stroke width is set to 0

Then one can see the following:
![artifacts](https://user-images.githubusercontent.com/33503784/38604478-0281408c-3d60-11e8-8dac-3d2e64ae9584.png)

**Comment by krogueintel** [comment]
Hi,

 I've done a bunch of work on filling and anti-aliased filling. Those artifacts above should be gone now, but I would love to hear additional feedback of any remaining artifacts.

**Comment by ChengCat** [comment]
I am running into a build issue now.

https://github.com/intel/fastuidraw/blob/78c235bb894e9b7361af95866b6fd07cff4c746c/demos/painter_path_test/main.cpp#L20

The included file "command_line_list.hpp" does not exist in the repository. Did you forget to add it into git?

**Comment by krogueintel** [comment]
Ah futz; I did forget that file. That file has now been added to the repo (via a squashed commit).

**Comment by ChengCat** [comment]
It's much better now, thanks! There's a small number of artifacts remaining, which can be noticed when slowly scaling the image inside the demo.

![artifact](https://user-images.githubusercontent.com/33503784/39283110-26f12476-48fc-11e8-9040-448e7b06fe49.png)

The demo is run as:
 ```
./painter-path-test-GL-release provide_auxiliary_image_buffer=auxiliary_buffer_interlock
```

**Comment by krogueintel** [comment]
Hmmm.. Looks like that the bevel between two anti- alias edges is not hitting any sample points... Or it bevels with an interior edge.... I'll look into it more; also can you run it with fill_alpha 0.5 to see if there is overdraw; you have an incredibly sharp eye so I appreciate if you spot additional issues

**Comment by ChengCat** [comment]
It looks good. I tried, and didn't spot any additional issues with `fill_alpha=0.5`.

**Comment by ChengCat** [comment]
It looks good. I don't spot any additional issues with `fill_alpha=0.5`.

**Comment by krogueintel** [comment]
I have not forgotten about this issue; I am looking into ways to solve this.

**Comment by ChengCat** [comment]
Thank you!

**Comment by krogueintel** [comment]
I've done some work that should help. Give it a try and see if there are still missing pixels.

**Comment by krogueintel** [comment]
I've changed the aa-fuzz creation a great deal and along the way did some git push -f to obliterate the idea of fixing it from previously in the week. This way that is in the repo now, should be much better. Give it a try, and feel free to try other paths by adding to the command line add_path_file FILE. There are a bunch of example paths in demo_data/paths. The file format is very simple:

- '[' indicates start of a contour
- ']' indicates the end of a contour
- '[[' indicates the start of a sequence of control points (FastUIDraw's API allows Bezier curves of any degree)
- ']]' indicates the end of a sequence of control points
- arc X indicates to connect the two point by an arc of X degree (instead of a Bezier curve or line segment)
- lastly, (x, y) specifies a coordinate (be it a point of the current contour or a control point).

**Comment by ChengCat** [comment]
Sorry for the delay, I was busy with some other things in the last few days. I noticed two issues:

1. The stroke looks to have an uneven width, when the stroke width is set to very small:

![selection_001](https://user-images.githubusercontent.com/33503784/41284590-4834ab74-6e29-11e8-950a-a1a0bd37e817.png)

2. It seems that there's some artifacts with fills:

![selection_002](https://user-images.githubusercontent.com/33503784/41284631-661d429a-6e29-11e8-9b32-54fea8ccdcc0.png)

For both issues, the demo is run as `./painter-path-test-GL-release provide_auxiliary_image_buffer=auxiliary_buffer_interlock`

**Comment by krogueintel** [comment]
Small stroke width (i.e. around 1 pixel effective) with shader based  anti-aliasing is always going to be unhappy.. But the continued shader based anti-aliasing filling issue... Sighs. It looks like one last way I have been thinking about I will need to do to get it pixel perfect (hopefully) . 

I will write up details as to what the shader based anti-aliasing is doing and from that, one will know why small widths give what the do.

One more sad note: the NVIDIA cards exhibit hw clipping bugs so when using nvidia do not use hw clipping (thus add painter_use_hw_clip_planes false to the command line).

**Comment by ChengCat** [comment]
> I will write up details as to what the shader based anti-aliasing is doing and from that, one will know why small widths give what the do.

Thanks. I am looking forward to that.

**Comment by krogueintel** [comment]
I've created a new branch: no-path-splitting-on-filling. Can you check if the artifacts are present on this branch. I am fervently hoping that they ARE present actually on this branch because what this branch does harms performance under extreme zoom massively. 

In addition, the painter-path-demo now shows in its display (activate the display by pressing the 'L' key) what is the current zoom and pan values along with command line options to set the pan-zoom values from the command line so that I can easily reproduce the visual issues.

**Comment by ChengCat** [comment]
Yes, there are some similar artifacts on the no-path-splitting-on-filling branch.

**Comment by krogueintel** [comment]
That is a relief; then the artifacts have (likely) nothing to do with the path splitting; There are two different ways I think I can resolve the issue. The first (easiest) only works for the usual fill rules (odd-even, non-zero) and their complements.. the second is more generic but really hard. I will keep you posted as I make progress...

**Comment by krogueintel** [comment]
Hi!!

 I am sorry that I have not provided updates on the issue; I have been busy with so many other things.

 First off, let me describe how the anti-aliasing works in filling currently. First and foremost: FastUIDraw does NOT use multi-sample anti-aliasing, instead it relies on a shader to compute/guess a reasonable coverage value. FastUIDraw performs filling as follows:

1. From a Path, fetch a TessellatedPath (via Path::tessellated_path(float)) that provides a tessellation fine enough for curves to look smooth.
2. From the TessellatedPath, fetch a FilledPath (via TessellatedPath::filled_path()). This object breaks the tessellated path (which is just a sequence of line segments) into a hierarchy (using a variant of Sutherland–Hodgman) where each piece can be triangulated separately. The motivation is that if the path is drawn zoomed in a great deal, only a small area of it is actually visible on the screen and triangulating the entire thing at once is computationally costly.
3. The triangulation is performed by a modified version of the tessellator found in GLUtess, that modification is located in the repo at src/3rd_party/glu_tess.  The key modifications are to take as input 2D points (instead of 3D so we can skip finding a plane) and the big modification is to emit all triangles the triangulation keyed by winding number. This ability gives FastUIDraw the data needed to fill a path by arbitrary fill rule.
4. Painter draws the triangulation of (3). This produces the filled path without anti-aliasing.
5. FilledPath also provides attribute and index data for all of the edges of the -boundary- for each winding number component. Painter draws these edges as 1-pixel thick with a shader to compute the anti-aliasing. The depth value used to draw the edges is so that which is drawn in (4) obscures where they overlap.

The render issue that you are seeing is likely caused by that the 1-pixel fuzz may not hit the sample point that would get the anti-alias render.

In truth, I am not really happy with how FastUIDraw is performing the anti-aliasing on filled paths because it adds pixels to the render. I had made several attempts to do the anti-alias by tweaking the coverage value of the triangles of the fill, but that ran into issues when there were very thin triangles that were the boundary triangles. In that case those triangles missed all sample points and their neighbors ended up being the effective boundary but there were not anti-aliased.

I have one more idea for anti-aliasing to try, but it is a mountain of work along with an API change for FilledPath. The worst part of the new way is that supporting arbitrary fill rules becomes much harder so I am now on the fence to drop arbitrary fill rules.

Just so you know, I am still looking into this! I really appreciate the issues reported and I really would like for you to continue to play with FastUIDraw (perhaps make an app or demo that looks neat) so that more issues can be found and addressed.

**Comment by krogueintel** [comment]
Lastly, as promised I will now write up how the anti-aliasing works on stroking.

There are two very different ways that anti-aliasing stroking is handled. The preferred way is cover then draw and the second is draw opaque then fuzz. The first way gives best render quality.

For cover then draw, the stroking is drawn in two passes. The first pass renders a coverage value to an offscreen buffer. If a fragment is covered more than once, the max value of the incoming coverage and current value is stored. The coverage value comes from a varying of the shaders that is 0 in the center and 1 on the boundary. The fragment shader uses that value along with its screen space derivatives (coming from GLSL dFdx and dFdy) to compute a coverage. Once the first pass is done, a second pass is done reading the value from the offscreen value and emitting that (along with clearing the offscreen buffer). The three ways how the auxiliary buffer is realized are: atomic ops (i.e. auxiliary_buffer_atomic), framebuffer fetch (auxiliary_buffer_framebuffer_fetch) or an interlock (auxiliary_buffer_interlock_main_only or auxiliary_buffer_interlock). The best performing option is going to usually be auxiliary_buffer_interlock, but sometimes it can be auxiliary_buffer_framebuffer_fetch. The worst performing option (by far) is auxiliary_buffer_atomic (because it forces draw breaks, uses atomics and makes the auxiliary buffer a staggering 32-bits per pixel).

For the other method, draw opaque then fuzz, first FastUIDraw draws the portion of the stroke that is fully covered (by drawing 1-pixel less on both sides of the stroke) and then drawing the entire thing again with full size but the first draw obscures the second. This gives reasonably ok rendering results but with artifacts of a pixel missing always where the stroke crosses itself and often at joins in the interior. 

For Intel hardware (as far back as IvyBridge), the first method is available with optimal performance (via auxiliary_buffer_interlock for GL and auxiliary_buffer_interlock_main_only for GLES) with new enough version of Mesa. Intel Gen9 (for example Skylake) GPU's can select to use framebuffer fetch instead. I have not done a thorough performance testing yet to see which way of doing auxiliary coverage is fastest on the various Gen9 GPU's.

**Comment by ChengCat** [comment]
Hi, glad to see your detailed explanations :)

I am considering to use FastUIDraw for a video game, which I am now working on full-time. FastUIDraw seems to have more features (e.g. clip paths) and promise better performance, but a safe alternative for me is [nanovg](https://github.com/memononen/nanovg). I am currently using nanovg, but am also prepared to switch to FastUIDraw when it's mature enough, e.g. artifacts would be unacceptable imperfections to the game. I haven't got around to benchmark FastUIDraw against nanovg yet.

Regarding the issue of anti-aliased fills, would extending the fuzz boundary to 2 pixels help?

nanovg support arbitrary fill rules via a stencil buffer, and the implementation is very simple, but I am not sure whether this method can help here.

**Comment by lieff** [comment]
There also https://github.com/mokafolio/Tarp as good alternative to nanovg.

**Comment by ChengCat** [comment]
@lieff I'll check it out. Thank you!

**Comment by krogueintel** [comment]
Hi,

 Can you try the current master (94be0ce0a5c16dd00203a1c731d9cacaf7cd6a07) ? It sets an option to painter-path-test to defaulted to true, that draws the AA-fuzz by simply stroking the original path with a stroke radius of 1.25 pixels using miter joins. In addition, it also defaults to linearizing from the arc-paths. 

 Please let me know if this removes some or preferably all render issues you have noticed (I did not see any this way, but I trust your eye for visual quality more than mine). If you do not see any issues, then I can do the work in Painter and FilledPath to extend this (hopefully easily) to arbitrary fill rules and avoiding the real hard way I was contemplating before.

**Comment by krogueintel** [comment]
Comments on performance:
- If you do not reuse your Path objects (i.e. constructing the Path object at every frame), the performance of FastUIDraw will suffer a great deal (because it will re-tessellate and recompute all sorts of additional data).

**Comment by ChengCat** [comment]
I tried 94be0ce, and the demo is run as `./painter-path-test-GL-release`. I only notice artifacts where fuzz boundary overlaps with other path segments. It becomes pretty obvious when stroke width is set to be small.

![94be0ce](https://user-images.githubusercontent.com/33503784/46670084-b96eb600-cbc0-11e8-9e35-fe4a145af678.png)

EDIT: I tried 'L' key mentioned above, but it doesn't work.

**Comment by ChengCat** [comment]
> If you do not reuse your Path objects (i.e. constructing the Path object at every frame), the performance of FastUIDraw will suffer a great deal (because it will re-tessellate and recompute all sorts of additional data).

Thanks for pointing this out! I hope there will be a Path variant which is cheap to create. This could be useful for both interactive multimedia applications and UI elements that are more dynamic than usual.

**Comment by krogueintel** [comment]
> I tried [94be0ce](https://github.com/intel/fastuidraw/commit/94be0ce0a5c16dd00203a1c731d9cacaf7cd6a07), and the demo is run as `./painter-path-test-GL-release`. I only notice artifacts where fuzz boundary overlaps with other path segments. It becomes pretty obvious when stroke width is set to be small.

This is for just checking if filling has anti-aliasing issues. 

Looking at the screen-shot it appears you did not add the option "provide_auxiliary_image_buffer" to the command line. For 1000 series NVIDIA cards you can do have "provide_auxiliary_image_buffer auxiliary_buffer_interlock_main_only" otherwise you need to do "provide_auxiliary_image_buffer auxiliary_buffer_atomic" to get the aa-fuzz nice where a path crosses itself. For Intel GPU's (starting with IvyBridge) with a new enough version of Mesa, the demos should automatically choose an option that avoids the artifacts where path stroking crosses itself.

Just to make sure, run the demos with the additional command line option "print_painter_config true" added.

**Comment by krogueintel** [comment]
Hi,

I've just pushed a series of changes (59e983e7b5b7aed7534d68390d8165d9e0ddab07) that should improve rendering quality and have best rendering quality out-of-the-box.

The option (for all demos) **painter_optimal_auto** can now be one of three values:
- **painter_no_optimal** indicates to use options from command line (or their default values)
- **painter_optimal_performance** indicates to initialize the Configuration with option that optimize performance. Options added to the command line explicitly will override any values set
- **painter_optimal_rendering** indicates to initialize the Configuration with option that optimize rendering quality. Options added to the command line explicitly will override any values set.

The default is **painter_optimal_rendering** which means on platforms that support GLES 3.1 or GL 4.2 or have the extension GL_ARB_shader_image_load_store should have optimal rendering quality for both path filling and stroking.

Please give it a try and also paste the output when the option **print_painter_config true** is added to the command line so I can see how the Painter is configured.

**Comment by ChengCat** [comment]
Sorry for the misunderstandings. I tried again with `./painter-path-test-GL-release print_painter_config=true`. The configuration is printed as below:


```
PainterBackendGL configuration:
                painter_verts_per_buffer:   262144  (requested 262144)
              painter_indices_per_buffer:   393216  (requested 393216)
               painter_blocks_per_buffer:    65536  (requested 65536)
                    painter_number_pools:        3  (requested 3)
          painter_break_on_shader_change:    false  (requested false)
              painter_use_hw_clip_planes:      off  (requested off)
            painter_uber_vert_use_switch:    false  (requested false)
            painter_uber_frag_use_switch:    false  (requested false)
            painter_use_uber_item_shader:        1  (requested 1)
       painter_uber_composite_use_switch:    false  (requested false)
painter_unpack_header_and_brush_in_frag_shader:    false  (requested false)
         painter_data_store_backing_type:     ssbo  (requested ssbo)
painter_assign_layout_to_vertex_shader_inputs:     true  (requested true)
       painter_assign_layout_to_varyings:     true  (requested true)
           painter_assign_binding_points:     true  (requested true)
            separate_program_for_discard:    false  (requested true)
          provide_auxiliary_image_buffer: auxiliary_buffer_atomic  (requested auxiliary_buffer_atomic)
                  painter_composite_type: dual_src  (requested dual_src)
          default_stroke_shader_aa_type:cover_then_draw (requested cover_then_draw)
            geometry_backing_store_type:       2
```

The artifacts are mostly gone. I only notice one type of artifact, that a pixel at a filled corner is missing.

![59e983e7](https://user-images.githubusercontent.com/33503784/46733280-5e4fc880-cc7f-11e8-9961-4a51c9ca63bf.png)

(I patched the font path to make 'L' key work this time.)

**Comment by krogueintel** [comment]
Likely this is from that the aa-fuzz of filling is using bevel joins instead of miter-joins. The painter-path-test demo has 3 different ways of drawing the anti-alias of fills:

1. High quality (default) which uses a two pass algorithm
2. Usual quality which uses a single pass algorithm; it has the weakness that some pixels might get dropped where the path crosses itself.
3. Anti-alias by stroking the path. This value is just to play with (since it gives utterly bogus results for any custom fill rules).

Hitting the 'u' key cycles through each of these modes. I suspect that anti-aliasing via stroking will remove the last artifact, give it a try and let me know. If it does, then I need to do the work of replacing the bevel joins with miter joins in the aa-fuzz of fills.

FWIW, using high quality anti-aliasing fill when the auxiliary buffer is type auxiliary_buffer_atomic will might harm performance quite a bit because each pass must have a glMemoryBarrier() which for many HW platforms stalls the GPU until the last draw completes (ick!).

I will likely tweak the Painter interface so that if the underlying backend is not harmed by high quality anti-aliasing, then the default anti-alias option would use that.

**Comment by krogueintel** [comment]
Hi,

 I've made a (hopefully) final series of commits to address the **all** the rendering issues for filling (and stroking); in particular joins from the path are drawn miter-style for the path fill anti-aliasing.

Firstly, the painter-path-demo interface has changed:
- pressing the 'a' will have the demo cycle through the anti-alias modes for stroking
- pressing the 'u' will have the demo cycle through the anti-alias modes for filling.

The anti-alias modes are:
- no_anti_alias : no anti-aliasing
- by_anti_alias_simple :  anti-alias method that does not rely on coverage auxiliary buffer. 
- by_anti_alias_hq : anti-alias method relies on coverage auxiliary buffer.
- by_anti_alias_auto : maps to by_anti_alias_simple or by_anti_alias_hq depending on if the hq path does not harm performance badly.

By harm performance badly, it essentially means that the auxiliary buffer is atomic.

If the render quality is good for the _hq mode we can finally close this issue.

**Comment by ChengCat** [comment]
I didn't notice any artifacts with the _hq mode.

Thank you!
