### ISSUE TITLE
Demos don't compile out of the box for wayland

### ISSUE THREAD

**Issue by gemath** [intel/fastuidraw#38]
When building for Wayland,  `demos/common/egl_helper.cpp`must be compiled with `-DSDL_VIDEO_DRIVER_WAYLAND`. If the config could set that automatically, everything would work out of the box.

**Comment by krogueintel** [comment]
Hi,

 I *think* that define is supposed to come from SDL2's SDL_config.h header. As far as I know, that define is used just in SDL_syswm.h to include the member struct that is referenced in egl_helper (specifically w.info.wl). The demos build out of the box under Ubuntu based distros and several others I have tested.

That it fails to build is quite troubling, what Linux distro does it not build under without adding the SDL_VIDEO_DRIVER_WAYLAND ?

-Kevin

**Comment by krogueintel** [comment]
I did a significant update: I removed the entire EGL binding system from the demos and FastUIDraw. It was made (quite some time ago) when I had encountered issues with letting SDL2 get an GLES context itself (the issue only manifested on one platform I tested and I suspect it was caused by an error I made). The upshot is that the demos transparently rely on SDL2 to do the right thing about the windowing system and getting a GL/GLES context instead of having an option to do it itself.

Let me know if this works fine for you and if it does, I will close the issue.

**Comment by krogueintel** [comment]
Did the latest commits resolve your issues?

**Comment by gemath** [comment]
You catch me on a vacation with a bad internet connection, give me a few days :o)

**Comment by gemath** [comment]
Sry for taking such a long time. It works for me now. In case it still matters: I use Void Linux with sway (Wayland compositor with XWayland support).
